# Generated by Django 4.1.3 on 2023-10-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('year', models.IntegerField(verbose_name='Возраст')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('number_films_made', models.IntegerField(verbose_name='Количество снятых фильмов')),
                ('number_main_roles', models.IntegerField(verbose_name='Количество главных ролей')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('year', models.IntegerField(verbose_name='Возраст')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('number_films_made', models.IntegerField(verbose_name='Количество снятых фильмов')),
                ('movie_category', models.CharField(max_length=250, verbose_name='Movie_category')),
            ],
        ),
    ]
