# Generated by Django 4.1.3 on 2023-10-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_create_director_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('data', models.DateTimeField(verbose_name='Возраст')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('number_main_roles', models.IntegerField(verbose_name='Количество главных ролей')),
            ],
        ),
    ]
